### ISSUE TITLE
Segfault : Sound card issue

### ISSUE THREAD

**Issue by Harvie** [swwa/audmes#4]
Just compiled on ArchLinux.

When i start it, i get following:

![image](https://user-images.githubusercontent.com/276504/112668079-55a6d900-8e5e-11eb-9ac8-9788f503db40.png)

So i go to menu and select `Tools->Audio Interface Configuration`, but it causes segfault with following backtrace:

```gdb
Thread 1 "AudMeS" received signal SIGSEGV, Segmentation fault.
0x0000555555598784 in AudioInterfaceDialog::SetDevices(RWAudioDevList, RWAudioDevList, unsigned long) ()
(gdb) bt
#0  0x0000555555598784 in AudioInterfaceDialog::SetDevices(RWAudioDevList, RWAudioDevList, unsigned long) ()
#1  0x0000555555589bd3 in MainFrame::OnSelectSndCard(wxCommandEvent&) ()
#2  0x00007ffff7865dde in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
    at /usr/lib/libwx_baseu-3.0.so.0
#3  0x00007ffff7865edc in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib/libwx_baseu-3.0.so.0
#4  0x00007ffff786621e in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#5  0x00007ffff78662ac in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#6  0x00007ffff7866382 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#7  0x00007ffff7d8323a in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/libwx_gtk2u_core-3.0.so.0
#8  0x00007ffff78660d7 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#9  0x00007ffff7d34c0f in wxMenuBase::SendEvent(int, int) () at /usr/lib/libwx_gtk2u_core-3.0.so.0
#10 0x00007ffff7c28c20 in  () at /usr/lib/libwx_gtk2u_core-3.0.so.0
#11 0x00007ffff69d6ddf in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff69fffbd in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff69f3cad in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff69f4210 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff6efcfb5 in gtk_widget_activate () at /usr/lib/libgtk-x11-2.0.so.0
#16 0x00007ffff6debdf1 in gtk_menu_shell_activate_item () at /usr/lib/libgtk-x11-2.0.so.0
#17 0x00007ffff6dec10f in  () at /usr/lib/libgtk-x11-2.0.so.0
#18 0x00007ffff6dd90a8 in  () at /usr/lib/libgtk-x11-2.0.so.0
#19 0x00007ffff69d6ddf in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff69ff9cb in  () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff69f32db in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff69f4210 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff6efe275 in  () at /usr/lib/libgtk-x11-2.0.so.0
#24 0x00007ffff6dd76d6 in gtk_propagate_event () at /usr/lib/libgtk-x11-2.0.so.0
#25 0x00007ffff6dd7b4b in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#26 0x00007ffff6c463be in  () at /usr/lib/libgdk-x11-2.0.so.0
#27 0x00007ffff68e2f9c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff6936a49 in  () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff68e2503 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff6dd69fe in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#31 0x00007ffff7b99876 in wxGUIEventLoop::DoRun() () at /usr/lib/libwx_gtk2u_core-3.0.so.0
#32 0x00007ffff773e37e in wxEventLoopBase::Run() () at /usr/lib/libwx_baseu-3.0.so.0
#33 0x00007ffff7704766 in wxAppConsoleBase::MainLoop() () at /usr/lib/libwx_baseu-3.0.so.0
#34 0x00007ffff7783199 in wxEntry(int&, wchar_t**) () at /usr/lib/libwx_baseu-3.0.so.0
#35 0x000055555557abe8 in main ()
```

**Comment by Harvie** [comment]
There is the same crash with AudMeS running in valgrind:

```
$ valgrind ./AudMeS 
==1528750== Memcheck, a memory error detector
==1528750== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1528750== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==1528750== Command: ./AudMeS
==1528750== 
--1528750-- WARNING: unhandled amd64-linux syscall: 315
--1528750-- You may be able to write your own handler.
--1528750-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--1528750-- Nevertheless we consider this a bug.  Please report
--1528750-- it at http://valgrind.org/support/bug_reports.html.


==1528750== Invalid read of size 8
==1528750==    at 0x14C784: AudioInterfaceDialog::SetDevices(RWAudioDevList, RWAudioDevList, unsigned long) (in /home/harvie/Temp/audmes/build/AudMeS)
==1528750==    by 0x13DBD2: MainFrame::OnSelectSndCard(wxCommandEvent&) (in /home/harvie/Temp/audmes/build/AudMeS)
==1528750==    by 0x50D8DDD: wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D8EDB: wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D921D: wxEvtHandler::TryHereOnly(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D92AB: wxEvtHandler::ProcessEventLocally(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D9381: wxEvtHandler::ProcessEvent(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x4CFA239: wxWindowBase::TryAfter(wxEvent&) (in /usr/lib/libwx_gtk2u_core-3.0.so.0.5.0)
==1528750==    by 0x50D90D6: wxEvtHandler::SafelyProcessEvent(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x4CABC0E: wxMenuBase::SendEvent(int, int) (in /usr/lib/libwx_gtk2u_core-3.0.so.0.5.0)
==1528750==    by 0x4B9FC1F: ??? (in /usr/lib/libwx_gtk2u_core-3.0.so.0.5.0)
==1528750==    by 0x5E04DDE: g_closure_invoke (in /usr/lib/libgobject-2.0.so.0.6800.0)
==1528750==  Address 0x38 is not stack'd, malloc'd or (recently) free'd
==1528750== 
==1528750== 
==1528750== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==1528750==  Access not within mapped region at address 0x38
==1528750==    at 0x14C784: AudioInterfaceDialog::SetDevices(RWAudioDevList, RWAudioDevList, unsigned long) (in /home/harvie/Temp/audmes/build/AudMeS)
==1528750==    by 0x13DBD2: MainFrame::OnSelectSndCard(wxCommandEvent&) (in /home/harvie/Temp/audmes/build/AudMeS)
==1528750==    by 0x50D8DDD: wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D8EDB: wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D921D: wxEvtHandler::TryHereOnly(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D92AB: wxEvtHandler::ProcessEventLocally(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x50D9381: wxEvtHandler::ProcessEvent(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x4CFA239: wxWindowBase::TryAfter(wxEvent&) (in /usr/lib/libwx_gtk2u_core-3.0.so.0.5.0)
==1528750==    by 0x50D90D6: wxEvtHandler::SafelyProcessEvent(wxEvent&) (in /usr/lib/libwx_baseu-3.0.so.0.5.0)
==1528750==    by 0x4CABC0E: wxMenuBase::SendEvent(int, int) (in /usr/lib/libwx_gtk2u_core-3.0.so.0.5.0)
==1528750==    by 0x4B9FC1F: ??? (in /usr/lib/libwx_gtk2u_core-3.0.so.0.5.0)
==1528750==    by 0x5E04DDE: g_closure_invoke (in /usr/lib/libgobject-2.0.so.0.6800.0)
==1528750==  If you believe this happened as a result of a stack
==1528750==  overflow in your program's main thread (unlikely but
==1528750==  possible), you can try to increase the size of the
==1528750==  main thread stack using the --main-stacksize= flag.
==1528750==  The main thread stack size used in this run was 8388608.
==1528750== 
==1528750== HEAP SUMMARY:
==1528750==     in use at exit: 4,198,873 bytes in 62,216 blocks
==1528750==   total heap usage: 262,492 allocs, 200,276 frees, 18,753,963 bytes allocated
==1528750== 
==1528750== LEAK SUMMARY:
==1528750==    definitely lost: 146,804 bytes in 569 blocks
==1528750==    indirectly lost: 218,316 bytes in 8,926 blocks
==1528750==      possibly lost: 2,041 bytes in 17 blocks
==1528750==    still reachable: 3,375,104 bytes in 48,808 blocks
==1528750==                       of which reachable via heuristic:
==1528750==                         newarray           : 21,312 bytes in 6 blocks
==1528750==         suppressed: 0 bytes in 0 blocks
==1528750== Rerun with --leak-check=full to see details of leaked memory
==1528750== 
==1528750== For lists of detected and suppressed errors, rerun with: -s
==1528750== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
(SIGSEGV) (core dumped)
```

**Comment by swwa** [comment]
Thanks for your report. What kind of sound card are you using? Do you have stereo input/microphone?

**Comment by Harvie** [comment]
No, i have mono input. Internal thinkpad soundcard. But i have stereo USB soundcard. I will try to connect it. However i am not sure if segfault is right way to handle mono soundcards anyway :-)

update: i set usb stereo soundcard as default source/sink in my system and it still crashes exactly the same way.

**Comment by swwa** [comment]
Right, it should not crash. I need information to reproduce and fix the issue - that's why I ask and I really appreciate your report! Are you using pulseaudio?

**Comment by Harvie** [comment]
> Are you using pulseaudio?

You will hate to hear this, but ArchLinux is mostly using PipeWire now. But applications should not really tell the difference between PA and PipeWire (unless they try to do something rather complex and pulse-specific)

If application decides to use ALSA API, it should work as well with PipeWire.

**Comment by swwa** [comment]
Oh, thanks. So far I tested on Debian and Ubuntu. Both run PA. In case of mono mic PA finds a output monitor device as input instead, which probably avoids the crash. So I will take a look at PipeWire and check ALSA.

May I contact you for testing when I have a fix?

**Comment by Harvie** [comment]
> May I contact you for testing when I have a fix?

Sure! I might even prepare ArchLinux package if i will find this tool useful.

**Comment by swwa** [comment]
Cool. I hope you do find it useful :-).

**Comment by swwa** [comment]
Please check out the branch "alsatest". I added fixes to avoid the crash. Still needs stereo input to run.

**Comment by Harvie** [comment]
Does not crash anymore, but there is no audio device to choose from:
![image](https://user-images.githubusercontent.com/276504/114103143-e0f58500-98c8-11eb-98c8-235646ce7cd3.png)

**Comment by swwa** [comment]
In the latest release I have implemented mono sound support. You may want to test it.
